// Simple script to load .env file and inject into environment
const fs = require('fs');
const path = require('path');

// Check multiple possible .env file locations
const possibleEnvPaths = [
  path.join(__dirname, '.env'),           // src/client/.env
  path.join(__dirname, '..', '.env'),     // src/.env
  path.join(__dirname, '..', '..', '.env') // root/.env
];

let envPath = null;
for (const possiblePath of possibleEnvPaths) {
  if (fs.existsSync(possiblePath)) {
    envPath = possiblePath;
    break;
  }
}

// Read .env file if it exists
let envVars = {};
if (envPath) {
  console.log(`Found .env file at: ${envPath}`);
  const envFile = fs.readFileSync(envPath, 'utf8');
  envFile.split('\n').forEach(line => {
    const trimmedLine = line.trim();
    if (trimmedLine && !trimmedLine.startsWith('#')) {
      const [key, ...valueParts] = trimmedLine.split('=');
      if (key && valueParts.length > 0) {
        envVars[key.trim()] = valueParts.join('=').trim();
      }
    }
  });
} else {
  console.log('⚠️  No .env file found. Looking in:');
  possibleEnvPaths.forEach(p => console.log(`   - ${p}`));
  console.log('\n💡 Create a .env file in src/client/ with: GROQ_API_KEY=your_key_here');
}

// Update environment files
const envDevPath = path.join(__dirname, 'src', 'environments', 'environment.ts');
const envProdPath = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');

const groqApiKey = envVars.GROQ_API_KEY || process.env.GROQ_API_KEY || '';

if (groqApiKey) {
  console.log('✅ Groq API key found and loaded!');
} else {
  console.log('⚠️  No GROQ_API_KEY found. Please add it to your .env file or set it manually in environment.ts');
}

const devContent = `// Auto-generated by load-env.js - DO NOT commit with API key!
export const environment = {
  production: false,
  groqApiKey: '${groqApiKey.replace(/'/g, "\\'")}'
};
`;

const prodContent = `// Auto-generated by load-env.js - DO NOT commit with API key!
export const environment = {
  production: true,
  groqApiKey: '${groqApiKey.replace(/'/g, "\\'")}'
};
`;

fs.writeFileSync(envDevPath, devContent);
fs.writeFileSync(envProdPath, prodContent);

console.log('✅ Environment files updated successfully!');

